window.COURSE_REGISTRY = window.COURSE_REGISTRY || {};
/* C-10 Electrical — California trade-exam practice questions.
   Original practice questions in the STYLE of the CSLB C-10 Trade exam — these are
   NOT actual exam questions. Organized on the official CSLB C-10 content outline
   (Planning & Estimation · Rough Wiring · Finish Wiring & Trim · Startup,
   Troubleshooting & Maintenance · Safety) and built on stable NEC / California
   Electrical Code (Title 24, Part 3) rules. EN + RU.

   ⚠ Verify every figure against the current code edition before relying on it.
   Code values change on the 3-year cycle (2025 CEC / 2023 NEC are current for 2026).
   This is a starter bank to expand toward the full set, like the other courses. */
window.COURSE_REGISTRY["c10-exam"] = [
  /* ── Planning & Estimation ─────────────────────────────────────────────── */
  { "id":1, "sec":"Planning & Estimation",
    "q":"A 240 V circuit supplies a load of 12 ohms. How much current does it draw?",
    "opts":["10 A","20 A","2,880 A","0.05 A"], "correct":1,
    "re":"Ohm's law: I = V ÷ R = 240 ÷ 12 = 20 A.",
    "qr":"Цепь 240 В питает нагрузку 12 Ом. Какой ток она потребляет?",
    "optsr":["10 A","20 A","2,880 A","0.05 A"],
    "rr":"Закон Ома: I = V ÷ R = 240 ÷ 12 = 20 A." },
  { "id":2, "sec":"Planning & Estimation",
    "q":"What is the power of a 120 V circuit drawing 15 A (unity power factor)?",
    "opts":["135 W","1,800 W","8 W","12,500 W"], "correct":1,
    "re":"Power P = V × I = 120 × 15 = 1,800 W.",
    "qr":"Какая мощность у цепи 120 В при токе 15 A (коэффициент мощности = 1)?",
    "optsr":["135 W","1,800 W","8 W","12,500 W"],
    "rr":"Мощность P = V × I = 120 × 15 = 1,800 W." },
  { "id":3, "sec":"Planning & Estimation",
    "q":"One horsepower is approximately equal to how many watts?",
    "opts":["746 W","550 W","1,000 W","100 W"], "correct":0,
    "re":"1 HP ≈ 746 watts (electrical).",
    "qr":"Одна лошадиная сила примерно равна скольким ваттам?",
    "optsr":["746 W","550 W","1,000 W","100 W"],
    "rr":"1 л.с. (HP) ≈ 746 ватт (электрических)." },
  { "id":4, "sec":"Planning & Estimation",
    "q":"A 240 V single-phase resistive load is rated 9,600 W. What current does it draw?",
    "opts":["20 A","40 A","80 A","4 A"], "correct":1,
    "re":"I = P ÷ V = 9,600 ÷ 240 = 40 A.",
    "qr":"Однофазная резистивная нагрузка 240 В рассчитана на 9,600 W. Какой ток?",
    "optsr":["20 A","40 A","80 A","4 A"],
    "rr":"I = P ÷ V = 9,600 ÷ 240 = 40 A." },
  { "id":5, "sec":"Planning & Estimation",
    "q":"The standard ampacity of 12 AWG copper at a 60°C termination is:",
    "opts":["15 A","20 A","30 A","25 A"], "correct":1,
    "re":"NEC Table 310.16, 60°C column: 12 AWG copper = 20 A (the familiar 14/12/10 → 15/20/30 rule).",
    "qr":"Стандартная допустимая нагрузка (ampacity) меди 12 AWG при клеммах 60°C:",
    "optsr":["15 A","20 A","30 A","25 A"],
    "rr":"NEC Table 310.16, колонка 60°C: медь 12 AWG = 20 A (правило 14/12/10 → 15/20/30)." },
  { "id":6, "sec":"Planning & Estimation",
    "q":"The standard ampacity of 10 AWG copper at a 60°C termination is:",
    "opts":["20 A","25 A","30 A","40 A"], "correct":2,
    "re":"NEC Table 310.16, 60°C column: 10 AWG copper = 30 A.",
    "qr":"Стандартная допустимая нагрузка меди 10 AWG при клеммах 60°C:",
    "optsr":["20 A","25 A","30 A","40 A"],
    "rr":"NEC Table 310.16, колонка 60°C: медь 10 AWG = 30 A." },
  { "id":7, "sec":"Planning & Estimation",
    "q":"A continuous load is 16 A. The branch-circuit conductor and OCPD must be rated at least:",
    "opts":["16 A","18 A","20 A","24 A"], "correct":2,
    "re":"Continuous loads are sized at 125%: 16 × 1.25 = 20 A (NEC 210.20(A) / 210.19(A)).",
    "qr":"Длительная (continuous) нагрузка 16 A. Проводник и автомат должны быть рассчитаны минимум на:",
    "optsr":["16 A","18 A","20 A","24 A"],
    "rr":"Длительные нагрузки берут с коэффициентом 125%: 16 × 1.25 = 20 A (NEC 210.20(A))." },
  { "id":8, "sec":"Planning & Estimation",
    "q":"What maximum voltage drop does the NEC recommend for a branch circuit?",
    "opts":["1%","3%","5%","10%"], "correct":1,
    "re":"The informational note to 210.19 recommends ≤3% on a branch circuit (≤5% total feeder + branch).",
    "qr":"Какое максимальное падение напряжения NEC рекомендует для ответвлённой цепи (branch)?",
    "optsr":["1%","3%","5%","10%"],
    "rr":"Примечание к 210.19 рекомендует ≤3% на branch-цепи (≤5% суммарно feeder + branch)." },
  { "id":9, "sec":"Planning & Estimation",
    "q":"For box-fill, what volume does a single 14 AWG conductor count as?",
    "opts":["1.50 in³","2.00 in³","2.25 in³","2.50 in³"], "correct":1,
    "re":"NEC Table 314.16(B): each 14 AWG conductor = 2.00 cubic inches.",
    "qr":"При расчёте заполнения коробки (box-fill) какой объём занимает один проводник 14 AWG?",
    "optsr":["1.50 in³","2.00 in³","2.25 in³","2.50 in³"],
    "rr":"NEC Table 314.16(B): один проводник 14 AWG = 2.00 кубических дюйма." },
  { "id":10, "sec":"Planning & Estimation",
    "q":"More than two conductors in a conduit may fill the raceway to a maximum of:",
    "opts":["31%","40%","53%","60%"], "correct":1,
    "re":"NEC Chapter 9, Table 1: 1 conductor = 53%, 2 = 31%, over 2 = 40%.",
    "qr":"Более двух проводников в трубе (conduit) могут заполнять её максимум на:",
    "optsr":["31%","40%","53%","60%"],
    "rr":"NEC Chapter 9, Table 1: 1 проводник = 53%, 2 = 31%, более 2 = 40%." },
  { "id":11, "sec":"Planning & Estimation",
    "q":"For a dwelling, the general lighting load is calculated at how many VA per square foot?",
    "opts":["1 VA/ft²","3 VA/ft²","5 VA/ft²","10 VA/ft²"], "correct":1,
    "re":"NEC 220.12: dwelling-unit general lighting load = 3 VA per square foot.",
    "qr":"Для жилого дома общая осветительная нагрузка считается как сколько VA на квадратный фут?",
    "optsr":["1 VA/ft²","3 VA/ft²","5 VA/ft²","10 VA/ft²"],
    "rr":"NEC 220.12: общая осветительная нагрузка жилья = 3 VA на квадратный фут." },
  { "id":12, "sec":"Planning & Estimation",
    "q":"The minimum service rating for a one-family dwelling is:",
    "opts":["60 A","100 A","125 A","200 A"], "correct":1,
    "re":"NEC 230.79(C): the service disconnect for a one-family dwelling must be at least 100 A, 3-wire.",
    "qr":"Минимальный номинал ввода (service) для одноквартирного дома:",
    "optsr":["60 A","100 A","125 A","200 A"],
    "rr":"NEC 230.79(C): ввод одноквартирного дома — не менее 100 A, 3-проводный." },

  /* ── Rough Wiring ──────────────────────────────────────────────────────── */
  { "id":13, "sec":"Rough Wiring",
    "q":"NM cable (Romex) must be secured at intervals not exceeding:",
    "opts":["3 ft","4½ ft","6 ft","10 ft"], "correct":1,
    "re":"NEC 334.30: NM cable is secured at least every 4½ ft.",
    "qr":"Кабель NM (Romex) должен крепиться с интервалом не более:",
    "optsr":["3 ft","4½ ft","6 ft","10 ft"],
    "rr":"NEC 334.30: кабель NM крепится минимум каждые 4½ фута." },
  { "id":14, "sec":"Rough Wiring",
    "q":"NM cable must be secured within how many inches of every box or fitting?",
    "opts":["8 in","12 in","18 in","24 in"], "correct":1,
    "re":"NEC 334.30: secure NM within 12 inches of each box, fitting, or cabinet.",
    "qr":"NM-кабель должен крепиться в пределах скольких дюймов от каждой коробки или фитинга?",
    "optsr":["8 in","12 in","18 in","24 in"],
    "rr":"NEC 334.30: крепить NM в пределах 12 дюймов от каждой коробки/фитинга." },
  { "id":15, "sec":"Rough Wiring",
    "q":"The minimum copper equipment grounding conductor (EGC) for a 20 A circuit is:",
    "opts":["14 AWG","12 AWG","10 AWG","8 AWG"], "correct":1,
    "re":"NEC Table 250.122: 20 A → 12 AWG copper EGC.",
    "qr":"Минимальный медный заземляющий проводник оборудования (EGC) для цепи 20 A:",
    "optsr":["14 AWG","12 AWG","10 AWG","8 AWG"],
    "rr":"NEC Table 250.122: 20 A → медный EGC 12 AWG." },
  { "id":16, "sec":"Rough Wiring",
    "q":"The minimum copper EGC for a 60 A circuit is:",
    "opts":["12 AWG","10 AWG","8 AWG","6 AWG"], "correct":1,
    "re":"NEC Table 250.122: up to 60 A → 10 AWG copper EGC.",
    "qr":"Минимальный медный EGC для цепи 60 A:",
    "optsr":["12 AWG","10 AWG","8 AWG","6 AWG"],
    "rr":"NEC Table 250.122: до 60 A → медный EGC 10 AWG." },
  { "id":17, "sec":"Rough Wiring",
    "q":"The minimum copper EGC for a 100 A circuit is:",
    "opts":["10 AWG","8 AWG","6 AWG","4 AWG"], "correct":1,
    "re":"NEC Table 250.122: 100 A → 8 AWG copper EGC.",
    "qr":"Минимальный медный EGC для цепи 100 A:",
    "optsr":["10 AWG","8 AWG","6 AWG","4 AWG"],
    "rr":"NEC Table 250.122: 100 A → медный EGC 8 AWG." },
  { "id":18, "sec":"Rough Wiring",
    "q":"Which of these is permitted to serve as an equipment grounding conductor?",
    "opts":["EMT (metal conduit)","PVC conduit","Wood molding","Nylon rope"], "correct":0,
    "re":"NEC 250.118: EMT and other metal raceways are listed EGCs; PVC (nonmetallic) is not.",
    "qr":"Что из перечисленного допускается использовать как заземляющий проводник (EGC)?",
    "optsr":["EMT (металлическая труба)","Труба PVC","Деревянный молдинг","Нейлоновый трос"],
    "rr":"NEC 250.118: EMT и другие металлические raceway — допустимые EGC; PVC (неметалл) — нет." },
  { "id":19, "sec":"Rough Wiring",
    "q":"The general minimum cover for direct-buried conductors (0–600 V) is:",
    "opts":["12 in","18 in","24 in","36 in"], "correct":2,
    "re":"NEC Table 300.5, direct-burial column: 24 inches of cover (some residential GFCI cases allow less).",
    "qr":"Общая минимальная глубина залегания для проводников прямой закладки (0–600 В):",
    "optsr":["12 in","18 in","24 in","36 in"],
    "rr":"NEC Table 300.5, колонка прямой закладки: 24 дюйма (для некоторых бытовых GFCI-цепей допускается меньше)." },
  { "id":20, "sec":"Rough Wiring",
    "q":"A grounding electrode conductor run only to a ground rod is not required to be larger than:",
    "opts":["8 AWG","6 AWG","4 AWG","2 AWG"], "correct":1,
    "re":"NEC 250.66(A): the GEC to a rod/pipe electrode need not exceed 6 AWG copper.",
    "qr":"Проводник к заземляющему электроду (GEC), идущий только к стержню (ground rod), не обязан быть крупнее:",
    "optsr":["8 AWG","6 AWG","4 AWG","2 AWG"],
    "rr":"NEC 250.66(A): GEC к стержневому электроду не обязан превышать 6 AWG меди." },
  { "id":21, "sec":"Rough Wiring",
    "q":"A single ground rod that does not measure 25 ohms or less must be supplemented by:",
    "opts":["1 additional electrode","2 additional electrodes","3 additional electrodes","Nothing"], "correct":0,
    "re":"NEC 250.53(A)(2): a single rod over 25 Ω is augmented with one additional electrode.",
    "qr":"Одиночный заземляющий стержень, не дающий 25 Ом или меньше, должен быть дополнен:",
    "optsr":["1 дополнительным электродом","2 дополнительными","3 дополнительными","Ничем"],
    "rr":"NEC 250.53(A)(2): одиночный стержень выше 25 Ом дополняется одним дополнительным электродом." },
  { "id":22, "sec":"Rough Wiring",
    "q":"In box-fill calculations, each device (switch/receptacle) yoke counts as:",
    "opts":["1× the largest conductor","2× the largest conductor","3× the largest conductor","Not counted"], "correct":1,
    "re":"NEC 314.16(B)(4): each yoke or strap = double the volume allowance of the largest conductor on it.",
    "qr":"При расчёте заполнения коробки каждая планка устройства (выключатель/розетка) считается как:",
    "optsr":["1× самого крупного проводника","2× самого крупного проводника","3× самого крупного проводника","Не учитывается"],
    "rr":"NEC 314.16(B)(4): каждая планка = двойной объём самого крупного подключённого к ней проводника." },
  { "id":23, "sec":"Rough Wiring",
    "q":"When 4 to 6 current-carrying conductors share a raceway, ampacity must be adjusted to:",
    "opts":["100%","80%","70%","50%"], "correct":1,
    "re":"NEC Table 310.15(C)(1): 4–6 current-carrying conductors → 80% of ampacity.",
    "qr":"Когда 4–6 токоведущих проводников идут в одной трубе, допустимый ток снижается до:",
    "optsr":["100%","80%","70%","50%"],
    "rr":"NEC Table 310.15(C)(1): 4–6 токоведущих проводников → 80% от ampacity." },

  /* ── Finish Wiring & Trim ──────────────────────────────────────────────── */
  { "id":24, "sec":"Finish Wiring & Trim",
    "q":"In a dwelling, no point along a wall floor line may be more than ___ from a receptacle.",
    "opts":["4 ft","6 ft","10 ft","12 ft"], "correct":1,
    "re":"NEC 210.52(A) — the '6-foot rule': a receptacle within reach so no point is over 6 ft away.",
    "qr":"В жилье ни одна точка вдоль линии пола стены не должна быть дальше ___ от розетки.",
    "optsr":["4 ft","6 ft","10 ft","12 ft"],
    "rr":"NEC 210.52(A) — «правило 6 футов»: розетка так, чтобы ни одна точка не была дальше 6 футов." },
  { "id":25, "sec":"Finish Wiring & Trim",
    "q":"Receptacles serving kitchen countertops must be:",
    "opts":["GFCI-protected","AFCI only","Unprotected","240 V only"], "correct":0,
    "re":"NEC 210.8(A): kitchen countertop receptacles require GFCI protection.",
    "qr":"Розетки, обслуживающие кухонные столешницы, должны быть:",
    "optsr":["Защищены GFCI","Только AFCI","Без защиты","Только 240 В"],
    "rr":"NEC 210.8(A): розетки кухонных столешниц требуют защиты GFCI." },
  { "id":26, "sec":"Finish Wiring & Trim",
    "q":"Receptacles installed in a dwelling bathroom must be:",
    "opts":["GFCI-protected","AFCI only","Unprotected","Switched"], "correct":0,
    "re":"NEC 210.8(A)(1): bathroom receptacles require GFCI protection.",
    "qr":"Розетки в ванной комнате жилья должны быть:",
    "optsr":["Защищены GFCI","Только AFCI","Без защиты","С выключателем"],
    "rr":"NEC 210.8(A)(1): розетки в ванной требуют защиты GFCI." },
  { "id":27, "sec":"Finish Wiring & Trim",
    "q":"The grounded (neutral) conductor must be identified by which color?",
    "opts":["White or gray","Green","Black","Red"], "correct":0,
    "re":"NEC 200.6: the grounded (neutral) conductor is white or gray.",
    "qr":"Каким цветом должен обозначаться заземлённый (нейтральный) проводник?",
    "optsr":["Белый или серый","Зелёный","Чёрный","Красный"],
    "rr":"NEC 200.6: заземлённый (нейтральный) проводник — белый или серый." },
  { "id":28, "sec":"Finish Wiring & Trim",
    "q":"An equipment grounding conductor may be identified as:",
    "opts":["Green or bare","White","Red","Blue"], "correct":0,
    "re":"NEC 250.119: an EGC is green, green-with-yellow-stripe, or bare.",
    "qr":"Заземляющий проводник оборудования (EGC) может обозначаться как:",
    "optsr":["Зелёный или голый","Белый","Красный","Синий"],
    "rr":"NEC 250.119: EGC — зелёный, зелёный с жёлтой полосой или голый (без изоляции)." },
  { "id":29, "sec":"Finish Wiring & Trim",
    "q":"In dwelling units, 125 V 15- and 20-A receptacles must be:",
    "opts":["Tamper-resistant","Weatherproof only","Rated 240 V","No special type"], "correct":0,
    "re":"NEC 406.12: 125 V, 15/20 A receptacles in dwellings must be tamper-resistant (TR).",
    "qr":"В жилых помещениях розетки 125 В на 15 и 20 A должны быть:",
    "optsr":["Защищены от детей (tamper-resistant)","Только влагозащищённые","На 240 В","Без особых требований"],
    "rr":"NEC 406.12: розетки 125 В, 15/20 A в жилье должны быть tamper-resistant (TR)." },

  /* ── Startup, Troubleshooting & Maintenance ────────────────────────────── */
  { "id":30, "sec":"Startup, Troubleshooting & Maintenance",
    "q":"Conductors to a single continuous-duty motor are sized at what percent of the motor FLC?",
    "opts":["100%","115%","125%","250%"], "correct":2,
    "re":"NEC 430.22: branch-circuit conductors for a single motor = 125% of the full-load current.",
    "qr":"Проводники к одиночному двигателю длительного режима выбирают как сколько процентов от FLC двигателя?",
    "optsr":["100%","115%","125%","250%"],
    "rr":"NEC 430.22: проводники branch-цепи для одного двигателя = 125% от тока полной нагрузки (FLC)." },
  { "id":31, "sec":"Startup, Troubleshooting & Maintenance",
    "q":"Overload protection for a motor with a service factor of 1.15 or more is set at:",
    "opts":["115% of FLC","125% of FLC","140% of FLC","175% of FLC"], "correct":1,
    "re":"NEC 430.32: motors with SF ≥ 1.15 (or temp rise ≤ 40°C) use 125% of FLC for overload.",
    "qr":"Защита от перегрузки двигателя с сервис-фактором 1.15 и выше устанавливается на:",
    "optsr":["115% от FLC","125% от FLC","140% от FLC","175% от FLC"],
    "rr":"NEC 430.32: для двигателей с SF ≥ 1.15 (или нагревом ≤ 40°C) перегрузка = 125% от FLC." },
  { "id":32, "sec":"Startup, Troubleshooting & Maintenance",
    "q":"A transformer with a 480 V primary and a 240 V secondary has a turns ratio of:",
    "opts":["1:2","2:1","4:1","1:4"], "correct":1,
    "re":"Turns ratio = primary ÷ secondary = 480 ÷ 240 = 2:1 (a step-down transformer).",
    "qr":"Трансформатор с первичной 480 В и вторичной 240 В имеет коэффициент трансформации:",
    "optsr":["1:2","2:1","4:1","1:4"],
    "rr":"Коэффициент = первичная ÷ вторичная = 480 ÷ 240 = 2:1 (понижающий трансформатор)." },
  { "id":33, "sec":"Startup, Troubleshooting & Maintenance",
    "q":"A Class A GFCI is designed to trip on a ground-fault current of about:",
    "opts":["4–6 mA","30 mA","15–20 A","100 mA"], "correct":0,
    "re":"Per UL 943, a Class A (personnel) GFCI trips at 4–6 mA of ground-fault current.",
    "qr":"GFCI класса A срабатывает при токе утечки на землю около:",
    "optsr":["4–6 mA","30 mA","15–20 A","100 mA"],
    "rr":"По UL 943 GFCI класса A (для защиты людей) срабатывает при 4–6 mA тока утечки." },
  { "id":34, "sec":"Startup, Troubleshooting & Maintenance",
    "q":"An AFCI device is intended to detect and respond to:",
    "opts":["Arcing faults","Ground faults to people","Overvoltage","Low power factor"], "correct":0,
    "re":"An AFCI detects arcing faults (a fire hazard). A GFCI, by contrast, protects people from shock.",
    "qr":"Устройство AFCI предназначено обнаруживать и реагировать на:",
    "optsr":["Дуговые замыкания (arc faults)","Утечку на человека","Перенапряжение","Низкий cos φ"],
    "rr":"AFCI обнаруживает дуговые замыкания (риск пожара). GFCI же защищает человека от удара током." },
  { "id":35, "sec":"Startup, Troubleshooting & Maintenance",
    "q":"Insulation resistance of a conductor is measured with a:",
    "opts":["Megohmmeter (megger)","Wattmeter","Tachometer","Oscilloscope"], "correct":0,
    "re":"A megohmmeter (megger) applies a high DC voltage to measure insulation resistance.",
    "qr":"Сопротивление изоляции проводника измеряют прибором:",
    "optsr":["Мегомметр (megger)","Ваттметр","Тахометр","Осциллограф"],
    "rr":"Мегомметр (megger) подаёт высокое постоянное напряжение и измеряет сопротивление изоляции." },
  { "id":36, "sec":"Startup, Troubleshooting & Maintenance",
    "q":"In the three-phase power formula P = √3 × VL × IL × PF, the √3 factor is about:",
    "opts":["1.414","1.732","3.000","0.866"], "correct":1,
    "re":"√3 ≈ 1.732, the line factor for balanced three-phase power.",
    "qr":"В формуле трёхфазной мощности P = √3 × VL × IL × PF множитель √3 примерно равен:",
    "optsr":["1.414","1.732","3.000","0.866"],
    "rr":"√3 ≈ 1.732 — линейный множитель для сбалансированной трёхфазной мощности." },
  { "id":37, "sec":"Startup, Troubleshooting & Maintenance",
    "q":"To reverse the rotation of a three-phase motor you:",
    "opts":["Swap any two line leads","Swap all three leads","Raise the voltage","Add a capacitor"], "correct":0,
    "re":"Interchanging any two of the three supply leads reverses a three-phase motor's rotation.",
    "qr":"Чтобы изменить направление вращения трёхфазного двигателя, нужно:",
    "optsr":["Поменять местами любые два линейных провода","Поменять все три провода","Поднять напряжение","Добавить конденсатор"],
    "rr":"Перестановка любых двух из трёх питающих проводов меняет направление вращения трёхфазного двигателя." },
  { "id":38, "sec":"Startup, Troubleshooting & Maintenance",
    "q":"Which instrument measures current without breaking the circuit?",
    "opts":["Clamp-on ammeter","Megger","Voltmeter","Wattmeter"], "correct":0,
    "re":"A clamp-on ammeter senses the conductor's magnetic field, so the circuit stays intact.",
    "qr":"Какой прибор измеряет ток без разрыва цепи?",
    "optsr":["Токовые клещи (clamp-on)","Megger","Вольтметр","Ваттметр"],
    "rr":"Токовые клещи считывают магнитное поле проводника, поэтому цепь не разрывается." },

  /* ── Safety ────────────────────────────────────────────────────────────── */
  { "id":39, "sec":"Safety",
    "q":"The purpose of Lockout/Tagout (LOTO) is to:",
    "opts":["Control hazardous energy during service","Label panel directories","Color-code conductors","Test power factor"], "correct":0,
    "re":"LOTO (Cal/OSHA Title 8 §3314) isolates and locks energy so equipment cannot be re-energized during work.",
    "qr":"Назначение блокировки/маркировки (Lockout/Tagout, LOTO):",
    "optsr":["Контроль опасной энергии при обслуживании","Подписать схему щита","Маркировать провода цветом","Измерить cos φ"],
    "rr":"LOTO (Cal/OSHA Title 8 §3314) изолирует и блокирует энергию, чтобы оборудование нельзя было включить во время работ." },
  { "id":40, "sec":"Safety",
    "q":"Receptacles used by personnel on a construction site must have:",
    "opts":["GFCI protection","AFCI protection","No protection","240 V only"], "correct":0,
    "re":"OSHA 1926.404(b): construction-site receptacles for personnel require GFCI protection.",
    "qr":"Розетки, которыми пользуется персонал на стройплощадке, должны иметь:",
    "optsr":["Защиту GFCI","Защиту AFCI","Без защиты","Только 240 В"],
    "rr":"OSHA 1926.404(b): розетки для персонала на стройке требуют защиты GFCI." },
  { "id":41, "sec":"Safety",
    "q":"The correct way to confirm a circuit is de-energized is to:",
    "opts":["Test, verify dead, retest on a known live source","Assume it is off","Read the breaker label only","Ask a coworker"], "correct":0,
    "re":"'Live-dead-live': prove the tester works on a known source before and after testing the circuit.",
    "qr":"Правильный способ убедиться, что цепь обесточена:",
    "optsr":["Проверить, убедиться что мертва, перепроверить на заведомо живом источнике","Считать что выключено","Только прочитать подпись автомата","Спросить коллегу"],
    "rr":"«Live-dead-live»: проверь тестер на заведомо живом источнике до и после проверки цепи." },
  { "id":42, "sec":"Safety",
    "q":"Arc-flash PPE, boundaries and safe work practices are covered by:",
    "opts":["NFPA 70E","NFPA 72","NFPA 101","NFPA 13"], "correct":0,
    "re":"NFPA 70E — Electrical Safety in the Workplace — covers arc-flash hazards and PPE.",
    "qr":"СИЗ от дуги (arc-flash), границы и безопасные приёмы работы регламентирует:",
    "optsr":["NFPA 70E","NFPA 72","NFPA 101","NFPA 13"],
    "rr":"NFPA 70E — «Электробезопасность на рабочем месте» — регламентирует риск дуги и СИЗ." },
  { "id":43, "sec":"Safety",
    "q":"If a victim of electric shock is still in contact with the live source, you first:",
    "opts":["De-energize the source","Pull them off with bare hands","Pour water on them","Finish the task first"], "correct":0,
    "re":"Never touch a victim in contact with live parts — shut off or disconnect the power first.",
    "qr":"Если пострадавший от удара током всё ещё в контакте с источником, сначала нужно:",
    "optsr":["Обесточить источник","Оттащить голыми руками","Облить водой","Сначала доделать работу"],
    "rr":"Нельзя касаться пострадавшего, пока он в контакте с током — сначала отключи питание." },
  { "id":44, "sec":"Safety",
    "q":"Near energized electrical work, a ladder should be:",
    "opts":["Fiberglass (nonconductive)","Aluminum","Steel","Copper-clad"], "correct":0,
    "re":"Use nonconductive (fiberglass) ladders near energized parts; metal ladders are a shock hazard.",
    "qr":"Рядом с работами под напряжением лестница должна быть:",
    "optsr":["Стеклопластиковая (непроводящая)","Алюминиевая","Стальная","С медным покрытием"],
    "rr":"Рядом с токоведущими частями используют непроводящие (стеклопластиковые) лестницы; металл опасен." },
  { "id":45, "sec":"Safety",
    "q":"Who may work within the restricted approach boundary of exposed energized parts?",
    "opts":["Qualified persons","Any worker","Apprentices alone","Visitors"], "correct":0,
    "re":"Only qualified persons (trained on the hazard) may cross the restricted approach boundary.",
    "qr":"Кто может работать в пределах ограниченной границы приближения к открытым токоведущим частям?",
    "optsr":["Квалифицированные лица","Любой работник","Ученики в одиночку","Посетители"],
    "rr":"Только квалифицированные лица (обученные риску) могут заходить за restricted-границу приближения." },
  { "id":46, "sec":"Safety",
    "q":"Minimum working-space depth in front of 0–150 V equipment (Condition 1) is:",
    "opts":["36 in (3 ft)","12 in","18 in","60 in"], "correct":0,
    "re":"NEC Table 110.26(A)(1): Condition 1 working depth for 0–150 V to ground = 3 ft.",
    "qr":"Минимальная глубина рабочего пространства перед оборудованием 0–150 В (Condition 1):",
    "optsr":["36 in (3 ft)","12 in","18 in","60 in"],
    "rr":"NEC Table 110.26(A)(1): глубина для Condition 1 при 0–150 В относительно земли = 3 фута." },
  { "id":47, "sec":"Safety",
    "q":"The minimum headroom of working space about electrical equipment is:",
    "opts":["6½ ft","5 ft","7½ ft","3 ft"], "correct":0,
    "re":"NEC 110.26(E): minimum headroom of working space = 6½ ft.",
    "qr":"Минимальная высота (headroom) рабочего пространства у электрооборудования:",
    "optsr":["6½ ft","5 ft","7½ ft","3 ft"],
    "rr":"NEC 110.26(E): минимальная высота рабочего пространства = 6½ фута." },
  { "id":48, "sec":"Safety",
    "q":"Which color may NOT be used to identify an ungrounded ('hot') conductor?",
    "opts":["White","Black","Red","Blue"], "correct":0,
    "re":"NEC 200.6/200.7: white and gray are reserved for the grounded conductor — not for a hot.",
    "qr":"Какой цвет НЕЛЬЗЯ использовать для фазного ('hot') проводника?",
    "optsr":["Белый","Чёрный","Красный","Синий"],
    "rr":"NEC 200.6/200.7: белый и серый зарезервированы для заземлённого проводника — не для фазы." },
  { "id":49, "sec":"Safety",
    "q":"How often should the TEST button on a GFCI be used to verify operation?",
    "opts":["Monthly","Once a year","Never","Only at install"], "correct":0,
    "re":"Manufacturers recommend pressing the GFCI TEST button monthly to confirm it trips.",
    "qr":"Как часто следует нажимать кнопку TEST на GFCI для проверки работоспособности?",
    "optsr":["Ежемесячно","Раз в год","Никогда","Только при установке"],
    "rr":"Производители рекомендуют нажимать кнопку TEST на GFCI ежемесячно, чтобы убедиться, что он срабатывает." },
  { "id":50, "sec":"Safety",
    "q":"Cal/OSHA's rule for working on electrical equipment is to:",
    "opts":["De-energize before work unless infeasible","Always work it energized","There is no requirement","Wear gloves and work it hot"], "correct":0,
    "re":"Establish an electrically safe (de-energized) condition before work unless de-energizing is infeasible.",
    "qr":"Правило Cal/OSHA для работы с электрооборудованием:",
    "optsr":["Обесточить до работы, если это выполнимо","Всегда работать под напряжением","Требования нет","Надеть перчатки и работать под напряжением"],
    "rr":"Сначала создать электробезопасное (обесточенное) состояние, если отключение в принципе выполнимо." }
];
